### ISSUE TITLE
README.md does not mention instructions on how to setup the MongoDB database

### ISSUE THREAD

**Issue by l2fprod** [watson-developer-cloud/investment-advisor#2]
The README.md is missing instructions on how to provision and initialize the MongoDB database. There is no reference that a MongoDB is needed and how to provision it.

**Comment by bultjern** [comment]
For anyone wondering how to do it:

On Bluemix:  Create and bind the service to run the application on bluemix. You also need to modify the credentials.js file (see below)

Locally: The experimental mongodb service within bluemix only allows for connection from within bluemix, so if you are using it, you need to run a local mongodb server and connect to it 

You can set the appropriate credentials by setting the database.url value within credentials.js to:

``` js
url : process.env.MONGODB ||
    function(){
      if(process.env.VCAP_SERVICES) {
        return JSON.parse(process.env.VCAP_SERVICES)['mongodb'][0]['credentials']['url'];
      }
      else {return false;}
    }()
    || "mongodb://localhost/db"
```
